### ISSUE TITLE
run installsubstrate.sh Error 

### ISSUE THREAD

**Issue by s2339956** [akemin-dayo/simject#78]
run `./configure --xcode-sdk=iphonesimulator --xcode-archs=x86_64` 

get log....

```
Will build iOS bootstrap.
Traceback (most recent call last):
  File "./configure", line 250, in <module>
    mconfig.finish_and_emit()
  File "./script/mconfig.py", line 1137, in finish_and_emit
    settings_root.emitter.emit()
  File "./script/mconfig.py", line 1027, in emit
    self.add_command_raw([makefile], list_mconfig_scripts(self.settings), cs_argvs)
  File "./script/mconfig.py", line 878, in list_mconfig_scripts
    if hasattr(mod, '__file__') and relpath_if_within(real_src, os.path.realpath(mod.__file__)):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/posixpath.py", line 394, in realpath
    filename = os.fspath(filename)
TypeError: expected str, bytes or os.PathLike object, not NoneType
```

macOS: 11.5.2
Xcode: 12.4
python 3.7.9

**Comment by PoomSmart** [comment]
Could you upgrade Python (use Python from brew instead)?

**Comment by PoomSmart** [comment]
Alternatively, update Xcode if there's one.

**Comment by s2339956** [comment]
Use the specified python
solved the problem


`#!/Library/Frameworks/Python.framework/Versions/3.8/bin/python3.8 `


```
/simject/substitute/configure
/simject/substitute/script/mconfig.py
/simject/substitute/script/gen-manual-mach.py
```
